/* Generated by AN DISI Unibo */ 
package it.unibo.source

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Source ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "init"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						forward("cmd", "cmd(h)" ,"robot" ) 
						delay(500) 
						forward("cmd", "cmd(h)" ,"robot" ) 
					}
				}	 
			}
		}
}
