/* Generated by AN DISI Unibo */ 
package it.unibo.tvocsentinel

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Tvocsentinel ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "init"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
					}
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
					}
					 transition(edgeName="t018",targetState="suspendRobot",cond=whenEvent("tvocHigh"))
					transition(edgeName="t019",targetState="wakeupRobot",cond=whenEvent("tvocLow"))
				}	 
				state("suspendRobot") { //this:State
					action { //it:State
						forward("suspend", "suspend(X)" ,"detector" ) 
					}
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("wakeupRobot") { //this:State
					action { //it:State
						forward("wakeup", "wakeup(X)" ,"detector" ) 
					}
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
			}
		}
}
