/* Generated by AN DISI Unibo */ 
package it.unibo.radar

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Radar ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("init")
						radarPojo.radarSupport.setUpRadarGui(  )
					}
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
						println("idle")
					}
					 transition(edgeName="t00",targetState="handlePolar",cond=whenRequest("polar"))
				}	 
				state("handlePolar") { //this:State
					action { //it:State
						println("handlePolar")
						if( checkMsgContent( Term.createTerm("polar(D)"), Term.createTerm("polar(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								radarPojo.radarSupport.update( payloadArg(0), "0"  )
								answer("polar", "polarReply", "polarReply(X)"   )  
						}
					}
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
			}
		}
}
