/* Generated by AN DISI Unibo */ 
package it.unibo.ctxConsole
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "192.168.43.184", this, "ventisette.pl", "sysRules.pl"
	)
}

